apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd # this ns is a must, as the project must be deployed in the same ns where argocd lives
spec:
  description: System-level cluster configurations
  sourceRepos:
    - '*'
  sourceNamespaces:
    - mock
  destinations:
    - namespace: 'mock*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'