apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-deployment
spec:
  template:
    spec:
      containers:
      - name: mock
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"